### ISSUE TITLE
Gem is breaking in my Action Workflow run

### ISSUE THREAD

**Issue by Tr3yb0** [orbit-love/community-ruby-dev-orbit#12]
I used the Orbit template to set up the Github Action, but when I run the Action I am getting an error:
ERROR:  Error installing dev_orbit:
	"setup" from dev_orbit conflicts with installed executable from orbit_activities
	
I'm not familiar with Ruby enough to know if there is something in my config which is causing this but it seems like this may be out of my control.

**Comment by bencgreenberg** [comment]
Hey @Tr3yb0!

Thanks for raising this. I released an update to the gem, which fixed this issue. I verified that the action has now been running successfully in your repo, and elsewhere again. 

Appreciate you calling attention to it. Enjoy the rest of your weekend!
