### ISSUE TITLE
Dev.to organization comments github action is failing

### ISSUE THREAD

**Issue by rdlauer** [orbit-love/community-ruby-dev-orbit#22]
We've had the dev.to Orbit integration running fine for a while now, but it just started throwing this error a couple days ago if anyone has any ideas!

```
Run dev_orbit --check-organization-comments
/opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/dev_orbit-0.5.1/lib/dev_orbit/dev.rb:86:in `get_articles': undefined method `empty?' for #<Net::HTTPForbidden 403 Forbidden Bots readbody=true> (NoMethodError)
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/dev_orbit-0.5.1/lib/dev_orbit/dev.rb:20:in `process_comments'
Checking for new DEV organization comments and posting them to your Orbit workspace...
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/dev_orbit-0.5.1/lib/dev_orbit/client.rb:72:in `organization_comments'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/dev_orbit-0.5.1/scripts/check_org_comments.rb:13:in `render'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/dev_orbit-0.5.1/bin/dev_orbit:54:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/bin/dev_orbit:23:in `load'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/bin/dev_orbit:23:in `<main>'
Error: Process completed with exit code 1.
```

**Comment by colinloretz** [comment]
Hi @rdlauer! Thanks for reporting this. We are taking a look at this right now. It appears to being blocked on the dev.to side so we are communicating with them to resolve. `Net::HTTPForbidden 403 Forbidden Bots`

**Comment by jgaskins** [comment]
@rdlauer DEV SRE here. @colinloretz is correct, DEV now blocks plain `Net::HTTP` unless the `User-Agent` header is set in an effort to crack down on folks scraping the site. It's easy to work around (simply set a header) but even so it's a surprisingly effective way to stop bots.

I'm about to post a PR to this repo setting this header as a workaround.

**Comment by jgaskins** [comment]
To be clear, this change was not intended to block usage of the API, so that's a bug on our end, but it's generally a good idea to set this header anyway.

**Comment by jgaskins** [comment]
The configuration bug on DEV has been [fixed](https://github.com/forem/forem/pull/15713) and that fix is live in production, so this should work again even without #23.

**Comment by colinloretz** [comment]
Thanks for the update and quick PR, @jgaskins! Merging in today and we'll be publishing an update to our gem.

**Comment by rdlauer** [comment]
Thanks everyone, looks great!
